# src/ai/mean_reversion_strategy.py

class MeanReversionStrategy:
    """
    Implements a simple mean reversion trading strategy.
    """
    def __init__(self, trading_env):
        """
        Initialize the strategy with the given trading environment.
        :param trading_env: The environment that provides price and market data.
        """
        self.trading_env = trading_env

    def get_signal(self):
        """
        Determine whether to buy or sell based on mean reversion.
        :return: 'buy', 'sell', or 'hold' based on the price compared to the moving average.
        """
        current_price = self.trading_env.get_current_price()
        moving_average = self.trading_env.get_moving_average()

        if current_price < moving_average:
            return "buy"
        elif current_price > moving_average:
            return "sell"
        else:
            return "hold"

    def execute_trade(self):
        """
        Execute a trade based on the signal generated by get_signal().
        """
        signal = self.get_signal()
        if signal == "buy":
            self.trading_env.buy()
        elif signal == "sell":
            self.trading_env.sell()
